{% set name = "langchain-community" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_community-{{ version }}.tar.gz
  sha256: b4694f34c7214dede03fe5a75e9f335e16bd788dfa6ca279302ad357bf0d0fc4

build:
  skip: true  # [py<39 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python
    - langchain <0.4.0,>=0.3.12
    - langchain-core <0.4.0,>=0.3.25
    - sqlalchemy <3,>=1.4
    - requests >=2.0.0,<3.0.0
    - pyyaml >=5.3
    - numpy >=1.22.4,<2.0.0  # [py<312]
    - numpy >=1.26.2,<3.0.0  # [py>=312]
    - aiohttp >=3.8.3,<4.0.0
    - tenacity >=8.1.0,!=8.4.0,<10
    - dataclasses-json >=0.5.7,<0.7
    - pydantic-settings >=2.4.0,<3.0.0
    - langsmith >=0.1.125,<0.3
    - httpx-sse >=0.4.0,<0.5.0

test:
  imports:
    - langchain_community
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: Community contributed LangChain integrations.
  description: Community contributed LangChain integrations.
  doc_url: https://api.python.langchain.com/en/stable/community_api_reference.html
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/community
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - baskaryan
    - hwchase17
    - efriis
    - agola11
