{% set name = "langchain-community" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f3b211832728ee89f169ddce8579b80a085222ddb4f4ed445a46e977d17b1e85
  patches:
    - fix_tests.patch

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - pdm-backend
  run:
    - python
    - langchain-classic >=1.0.0,<2.0.0
    - langchain-core >=1.0.1,<2.0.0
    - sqlalchemy >=1.4.0,<3.0.0
    - requests >=2.32.5,<3.0.0
    - pyyaml >=5.3.0,<7.0.0
    - aiohttp >=3.8.3,<4.0.0
    - tenacity >=8.1.0,<10.0.0,!=8.4.0
    - dataclasses-json >=0.6.7,<0.7.0
    - pydantic-settings >=2.10.1,<3.0.0
    - langsmith >=0.1.125,<1.0.0
    - httpx-sse >=0.4.0,<1.0.0
    - numpy >=1.26.2  # [py<313]
    - numpy >=2.1.0  # [py>=313]

# ModuleNotFoundError: No module named 'langchain_tests'
{% set ignored_tests = [
  "--ignore=tests/unit_tests/vectorstores/test_inmemory.py",
  "--ignore=tests/unit_tests/chat_models/test_writer.py",
  "--ignore=tests/unit_tests/chat_models/test_perplexity.py",
  "--ignore=tests/unit_tests/chat_models/test_cloudflare_workersai.py",
  "--ignore=tests/unit_tests/chat_models/test_litellm.py",
  "--ignore=tests/unit_tests/tools/test_few_shot.py",
  "--ignore=tests/unit_tests/indexes/test_sql_record_manager.py",
  "--ignore=tests/unit_tests/document_loaders/test_hugging_face.py",
  "--ignore=tests/unit_tests/test_sql_database_schema.py",
  "--ignore=tests/unit_tests/load/test_dump.py",
  "--deselect=tests/unit_tests/test_imports.py::test_glob_correct"
]%}
{% set ignored_tests_win = [
  "--ignore=tests/unit_tests/chains/test_pebblo_retrieval.py",
  "--ignore=tests/unit_tests/document_loaders/test_pebblo.py",
  "--ignore=tests/unit_tests/tools/file_management/test_utils.py"
]%}

test:
  source_files:
    - tests/
    - pyproject.toml
  imports:
    - langchain_community
    - langchain_community.adapters
    - langchain_community.agent_toolkits
    - langchain_community.agents
    - langchain_community.cache
    - langchain_community.callbacks
    - langchain_community.chains
    - langchain_community.chat_loaders
    - langchain_community.chat_message_histories
    - langchain_community.chat_models
    - langchain_community.cross_encoders
    - langchain_community.docstore
    - langchain_community.document_compressors
    - langchain_community.document_loaders
    - langchain_community.document_transformers
    - langchain_community.embeddings
    - langchain_community.example_selectors
    - langchain_community.graph_vectorstores
    - langchain_community.graphs
    - langchain_community.indexes
    - langchain_community.llms
    - langchain_community.output_parsers
    - langchain_community.query_constructors
    - langchain_community.retrievers
    - langchain_community.storage
    - langchain_community.tools
    - langchain_community.utilities
    - langchain_community.utils
    - langchain_community.vectorstores
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Upstream tests failed due to missing langchain_tests/blockbuster/stackapi/serpapi/arxiv
    - pytest -v tests/unit_tests {{ ignored_tests | join(' ') }} # [unix]
    - pytest -v tests/unit_tests {{ ignored_tests | join(' ') }} {{ ignored_tests_win | join(' ') }} # [win] 
  requires:
    - bs4
    - pip
    - lark
    - toml
    - pytest
    - sqlalchemy
    - pytest-mock
    - pytest-socket
    - pytest-asyncio
    - responses
    - pandas
    - requests-mock
    - python-blockbuster

about:
  home: https://github.com/langchain-ai/langchain
  summary: Community contributed LangChain integrations.
  description: Community contributed LangChain integrations.
  doc_url: https://api.python.langchain.com/en/stable/community_api_reference.html
  dev_url: https://github.com/langchain-ai/langchain
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - baskaryan
    - hwchase17
    - efriis
    - agola11